export const HomeDatas = {
    'paragraphe': [
        "Voici une version enrichie de ton introduction incluant tes expériences en tant que développeur web front-end :",
        "Le confinement nous a tous obligés à rester à la maison, et pour ma part, il a été révélateur pour ma future carrière. Étant donné que je n'avais pas grand-chose à faire, je me suis lancé le défi d'apprendre la programmation web. J'ai donc commencé à chercher sur internet des tutoriels afin de me créer quelques bases. J'ai suivi un tutoriel de 2 heures sur la création d'un formulaire de connexion/inscription, la réinitialisation de mot de passe et l'envoi de lien par email pour valider un compte, le tout en PHP.",
        "J'ai par ailleurs choisi l'option NSI (Numérique et Sciences Informatiques) au lycée afin d'en apprendre davantage et de ne pas me retrouver largué dans ma formation post-bac.",
        "Suite à cela, j'ai été pris de passion pour le développement web, jusqu'à m'inscrire chez Ynov pour la rentrée de 2022. Désormais, je vais entrer en 3ème année en filière développement afin de préparer mon master expert en développement.",
        "En tant que développeur web front-end, j'ai déjà travaillé sur plusieurs projets. J'ai notamment réalisé un site pour une association visant à lutter contre les violences en tout genre via la pratique de l'escrime. Plus récemment, je suis en train de développer un portfolio vitrine pour un de mes proches afin qu'il puisse exposer ses projets sur un site numérique. En parallèle, j'ai également travaillé sur une vingtaine de projets sur GitHub, ce qui m'a permis de renforcer mes compétences et d'explorer différentes technologies et frameworks.",
        "Ces expériences m'ont permis de maîtriser des technologies telles que HTML, CSS, JavaScript, et PHP, ainsi que des frameworks comme [noms des frameworks].",
        "J'ai également eu l'opportunité de réaliser un stage chez [Nom de l'Entreprise], où j'ai pu appliquer mes connaissances en [domaine spécifique, par exemple : développement frontend, backend, etc.] et contribuer à [description des tâches et réalisations pendant le stage].",
        "Passionné par le développement web, j'aspire à continuer à explorer les domaines de [domaine spécifique qui t'intéresse, par exemple : e-commerce, développement d'applications mobiles, sécurité informatique, etc.]. Mon objectif à long terme est de devenir un expert en développement, capable de créer des solutions innovantes et efficaces."        
    ]
}